# Generated by Django 3.0.7 on 2020-07-23 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('display', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('category', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('address', models.TextField(max_length=10000)),
                ('number', models.IntegerField()),
                ('back_image', models.ImageField(upload_to='products/')),
                ('icon', models.ImageField(upload_to='icons/')),
                ('desc', models.TextField(max_length=10000)),
                ('whatsapp', models.URLField(max_length=255)),
                ('twitter', models.URLField(max_length=255)),
                ('instagram', models.URLField(max_length=255)),
                ('facebook', models.URLField(max_length=255)),
                ('email', models.URLField(max_length=255)),
                ('imageone', models.ImageField(upload_to='gallery/')),
                ('imagetwo', models.ImageField(upload_to='gallery/')),
                ('imagethree', models.ImageField(upload_to='gallery/')),
                ('imagefour', models.ImageField(upload_to='gallery/')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('product_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_hunter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
